### ISSUE TITLE
officeInstallProgress % required 

### ISSUE THREAD

**Issue by mani2care** [acodega/dialog-scripts#1]
hey reg this /officeInstallProgress.sh script can add that download % in dialog so the user will see its what is in stage.

**Comment by acodega** [comment]
Did your message get cut off? I'm unsure what you're asking.

**Comment by mani2care** [comment]
Looking for application download percentage and install status in added advantage.

for example MS office is very big file so if its visible to enduser how much its got downloaded then they will happy too see

**Comment by acodega** [comment]
The script will show download percentage, but it doesn't show detailed status for install progress.

**Comment by mani2care** [comment]
Sorry i tried is did not get any download percentage in UI.

Thanks & Regards,

Manikandan R
Contact: +91-9902103878
E-mail: ***@***.***

**Comment by acodega** [comment]
Do you have any logs from the script running?
