### ISSUE TITLE
dialog-scripts/officeInstallProgress.sh

### ISSUE THREAD

**Issue by mani2care** [acodega/dialog-scripts#2]
Hi , 

i tried using that [dialog-scripts](https://github.com/acodega/dialog-scripts)/officeInstallProgress.sh

having issue during the download process internet connection failed and its not giving any error and not downloading after 

looking for your support to fix the issue with internet connection validation and  between any internet connection drop and retry option to add it at-least 3 attempt.

**Comment by acodega** [comment]
Unfortunately I don't think I'll have the time to be working on this any time soon.
